title: Abdelkrim.blog
tagline: Personal Tech Blog
description: Join me on a journey through software architecture, design, and engineering, as we delve into the world of programming, coding, C#, .NET, Flutter, and Dart. Learn about effective project management and discover ways to nurture your software engineering career. Let's explore together the ins and outs of building great software while sharing insights and tips for personal growth.
author: Abdelkrim Bourennane
locale: en_US
email: "abdelkrim.bournane@gmail.com"

url: "https://abdelkrim.blog"

twitter_username: karimkos
github_username:  karimkod
linkedin_username: abdelkrim-bournane

show_excerpts: true


theme: minima

disqus: 
  shortname: abdelkrim-blog

gems:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed
