title: Abdelkrim.blog
author: Abdelkrim Bourennane
email: "abdelkrim.bournane@gmail.com"

url: "https://abdelkrim.blog"

twitter_username: karimkos
github_username:  karimkod
instagram_username: codewkarim
linkedin_username: abdelkrim-bournane
youtube_username: "@codewkarim"

theme: minima

gem:
    - jekyll-seo-tag
