title: Abdelkrim's Blog
author: Abdelkrim Bourennane
email: "abdelkrim.bournane@gmail.com"
  
twitter_username: karimkos
github_username:  karimkod
instagram_username: codewkarim
linkedin_username: abdelkrim-bournane
youtube_username: "@codewkarim"

theme: minima
